/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dental.surgery.management.system.panel;

import dental.surgery.management.system.process.Processor;

/**
 *
 * 
 */
public class ProcedurePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcedurePanel
     */
    public ProcedurePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        procedureTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        procedureCostTextField = new javax.swing.JTextField();
        procedureNameTextField = new javax.swing.JTextField();
        saveProcedureButton = new javax.swing.JButton();
        deleteProcedureButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(671, 469));

        procedureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        procedureTable.addMouseListener (new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = procedureTable.rowAtPoint(evt.getPoint());
                int col = procedureTable.columnAtPoint(evt.getPoint());
                if (row >= 0 && col >= 0) {
                    int procedureId = (int) procedureTable.getModel().getValueAt(row, 0);
                    loadRecord(procedureId);
                }
            }
        });
        jScrollPane1.setViewportView(procedureTable);
        procedureTable.getColumnModel().getColumn(0).setMinWidth(30);
        procedureTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        procedureTable.getColumnModel().getColumn(0).setMaxWidth(30);

        jLabel1.setText("Name");

        jLabel3.setText("Cost");

        saveProcedureButton.setText("Save");
        saveProcedureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProcedureButtonActionPerformed(evt);
            }
        });

        deleteProcedureButton.setText("delete");
        deleteProcedureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProcedureButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(procedureNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(procedureCostTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(saveProcedureButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(deleteProcedureButton))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procedureNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procedureCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveProcedureButton)
                            .addComponent(deleteProcedureButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveProcedureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProcedureButtonActionPerformed
        if(procedureCostTextField.getText()!=null && procedureNameTextField.getText()!=null){
            double cost = Double.valueOf(procedureCostTextField.getText());
            Processor.saveProcedure(procedureNameTextField.getText(), cost);
            procedureCostTextField.setText(null);
            procedureNameTextField.setText(null);
        }
    }//GEN-LAST:event_saveProcedureButtonActionPerformed

    private void  loadRecord(int procedureId){
        
    }
    
    private void deleteProcedureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProcedureButtonActionPerformed
        int rowId = procedureTable.getSelectedRow();
        if (rowId > -1) {
            int procedureId = (int) procedureTable.getModel().getValueAt(rowId, 0);
            Processor.deleteProcedure(procedureId);
        }
    }//GEN-LAST:event_deleteProcedureButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteProcedureButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField procedureCostTextField;
    private javax.swing.JTextField procedureNameTextField;
    public static javax.swing.JTable procedureTable;
    private javax.swing.JButton saveProcedureButton;
    // End of variables declaration//GEN-END:variables
}
